# Generated by Django 4.2.13 on 2026-02-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentlog",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("Office Order", "Office Order"),
                    ("Circular", "Circular"),
                    ("Policy", "Policy"),
                    ("Notice", "Notice"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
