# Generated by Django 4.2.28 on 2026-02-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0002_add_policy_document_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="documentlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="documentlog",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("Office Order", "Office Order"),
                    ("Circular", "Circular"),
                    ("Policy", "Policy"),
                    ("Notice", "Notice"),
                    ("Other", "Other"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="documentlog",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("hi", "हिंदी (Hindi)")],
                default="en",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="documentlog",
            name="reference_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
