# Generated by Django 5.2.11 on 2026-03-03 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_add_db_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document Log (Legacy)'},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, editable=False, help_text='Auto-assigned unique serial: BISAG-OO-YYYY-NNNNN', max_length=30, unique=True)),
                ('document_type', models.CharField(choices=[('office', 'Office Order'), ('circular', 'Circular'), ('policy', 'Policy')], db_index=True, max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'हिंदी (Hindi)')], default='en', max_length=5)),
                ('reference_id', models.CharField(blank=True, help_text='Reference / file number shown on document', max_length=300)),
                ('date_raw', models.CharField(blank=True, help_text='Date in YYYY-MM-DD format', max_length=20)),
                ('subject', models.TextField(blank=True)),
                ('body_prompt', models.TextField(blank=True, help_text='AI generation prompt text')),
                ('body', models.TextField(blank=True, help_text='Generated document body text')),
                ('from_position', models.CharField(blank=True, max_length=200)),
                ('to_data', models.JSONField(blank=True, default=list)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1, help_text='Increments each time the document is edited')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Document',
                'verbose_name_plural': 'Generated Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='generator_g_user_id_f6acad_idx'), models.Index(fields=['document_type', '-created_at'], name='generator_g_documen_5bf374_idx'), models.Index(fields=['serial_number'], name='generator_g_serial__e96e87_idx')],
            },
        ),
    ]
